// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofrimzwahocfigiyimhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcmltendhaG9jZmlnaXlpbWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTU3OTQsImV4cCI6MjA3MjYzMTc5NH0.wYzctgGBpA7ScM-J7cZ5lfw8JL4R4Y4IV_a8O5FG0lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});